<?php

namespace App\Services\PaymentProcessors;

use App\Services\PaymentProcessors\Dtos\CreateCustomerDto;
use App\Services\PaymentProcessors\Dtos\CreatePaymentDto;

class FakePaymentProcessor implements PaymentProcessor
{
    public function createCustomer(CreateCustomerDto $data): string|int
    {
        return uniqid('cus_');
    }

    public function createPayment(CreatePaymentDto $data): array
    {
        $output = [
            'paymentId' => uniqid('pay_'),
            'pixQrCode' => null,
            'pixCopiaCola' => null,
            'bankSlipUrl' => null,
            'credit_card_brand' => null,
            'credit_card_token' => null,
            'credit_card_last_digits' => null,
            'status' => strtolower($data->billingType) === 'credit_card' ? 'paid' : 'pending',
        ];

        if (strtolower($data->billingType) === 'boleto') {
            $output['bankSlipUrl'] = config('app.url');
        }

        if (strtolower($data->billingType) === 'pix') {
            $output['pixQrCode'] = 'iVBORw0KGgoAAAANSUhEUgAAAYsAAAGLCAIAAAC5gincAAAOW0lEQVR42u3bQZIjNxADQP3/0+sf+DIsFMhOXDWWusli0hGI/f0TEWnNzxKICKFERAglIoQSESGUiBBKRIRQIiKEEhFCiYgQSkQIJSJCKBERQokIoURECCUihBIRIZSICKFEhFAiIoQSEUKJiBBKRIRQIkIoEZFyoX6p/P/vxj49uFZ/Wdi5LZvb/ZIxO/gKf9nQv3w694IHF5ZQhCIUoQhFKEIRilCEIhShCEUoQhGKUIT6sFCxb44ZNLdJc0v3F5Jiytyo6gO7f8c3E4pQhCIUoQhFKEIRilCEIhShCEUoQhGKUE8JFWvrSs7VVvcxNzolTd+cIyUl6dZFGKsyCUUoQhGKUIQiFKEIRShCEYpQhCIUoQhFKELF37/Evs5/UtB5REtk/Mv+dl6ihCIUoQhFKEIRilCEIhShCEUoQhGKUIQiFKEI9eenGtyGsTJra4JjCxtzJOZ1yaeEIhShCEUoQhGKUIQiFKEIRShCEYpQhCIUobaboLnBih2V2GrMFVJbizNHcKe5nZq3fDOhCEUoQhGKUIQiFKEIRShCEYpQhCIUoQh1t1Cx/fapT316bxtLKJ/61KeEIpRPfUooQpkzn/qUUITyqU8J9ZZQW4l1WwcLx9gblUzh1h7N/e7cMJTQ0HK6CUUoQhGKUIQiFKEIRShCEYpQhCIUoQhFqKeE2mrrSmqUzs6lJAelOHie5/54bq5iq/Fgl0coQhGKUIQiFKEIRShCEYpQhCIUoQhFKEItGLS1drE2J7bBsbXqnO+53d9Cp+SZSypFQhGKUIQiFKEIRShCEYpQhCIUoQhFKEIR6vIur3OT5rYwVmUe7AHnNiVWg8YcKbn5ti6GOYMIRShCEYpQhCIUoQhFKEIRilCEIhShCEWot4TqnLO5352b/q1erOQF53Y/thpz9m1d3oQiFKEIRShCEYpQhCIUoQhFKEIRilCEIhShBkb24CEsqVHmarKtLu8KVt5rNreOVSn9hCIUoQhFKEIRilCEIhShCEUoQhGKUIQi1GVCdW7wXLUXY/SBknTL3JI7JtaavdeZEopQhCIUoQhFKEIRilCEIhShCEUoQhGKUF/q8m6syTrLrNhabQkVu+putC92XcXAIhShCEUoQhGKUIQiFKEIRShCEYpQhCIUoW4T6mDXM3cmY5xtVYqx6S8RubPqmrO+ZHEIRShCEYpQhCIUoQhFKEIRilCEIhShCEUoQl11CEvc3HrIGLJzB7iz5411arF7seSrCEUoQhGKUIQiFKEIRShCEYpQhCIUoQhFqMuFmjuEc3s211+UYDd3E1xRv25td2ydSzaFUIQiFKEIRShCEYpQhCIUoQhFKEIRilCEIlR3bxJTNXbaY091cAe37pjY+8bK6BubXEIRilCEIhShCEUoQhGKUIQiFKEIRShCEerDQnWWLLH/dqutix2k2KmbkzFWN8cOztzibOlGKEIRilCEIhShCEUoQhGKUIQiFKEIRShCvSVUrAccXKzn+qmSZnPrBto6hLEeMAYWoQhFKEIRilCEIhShCEUoQhGKUIQiFKEIRaiBXSnpxTofI9a4laxkzK/YRVji9VZlTChCEYpQhCIUoQhFKEIRilCEIhShCEUoQn1JqFi5E5vC2PZvLXtnx/Rezxv7qgdCKEIRilCEIhShCEUoQhGKUIQiFKEIRShC3SZUSTUQKw23BmurY4qhs3UDHdyFubXaqufW6CcUoQhFKEIRilCEIhShCEUoQhGKUIQiFKEuE+qKgS45KrG12vI6dj+VlMJzl8pWtVdSGhKKUIQiFKEIRShCEYpQhCIUoQhFKEIRilBfEmpuV0qmoeSNSrqezgspZu5BKGOzsXYREopQhCIUoQhFKEIRilCEIhShCEUoQhGKUB8SKnaAY8psVTBzQznXBM0t7FaFGqtBY46sTSyhCEUoQhGKUIQiFKEIRShCEYpQhCIUoQh1t1Cx+mauzigplWJPFdNt641ix+zgD5XUcw92eYQiFKEIRShCEYpQhCIUoQhFKEIRilCEItRClxc7sbGF3jKocwrnPp0bs63X35rJfxeGUIQiFKEIRShCEYpQhCIUoQhFKEIRilCEuk2oGxuZrWmYG+gr+po5kWN7NNdd3rg4d3R5hCIUoQhFKEIRilCEIhShCEUoQhGKUIQi1H6Xt7X9MexKZNwqlWKcxYZwbpBKmtxY30ooQhGKUIQiFKEIRShCEYpQhCIUoQhFKEJ9SahOGubm++DYbT3zwTeau3LmnvmKqSvp8raOM6EIRShCEYpQhCIUoQhFKEIRilCEIhShCHWbUAeHcu5sxISam6TYY/xSyY370rLHjlXnOSIUoQhFKEIRilCEIhShCEUoQhGKUIQiFKEIdaJH2KqcYr3JVnk3p+pcE9RZOc1NbMk5mvtdQhGKUIQiFKEIRShCEYpQhCIUoQhFKEIR6i2h5t6wpPqJdWolqzH3VFuF49weddq3dSERilCEIhShCEUoQhGKUIQiFKEIRShCEYpQhIqfq7nuY+6obI17yR7NLc5WIXXw9oq1olf4RShCEYpQhCIUoQhFKEIRilCEIhShCEUoQt0m1FxttHW8Y2P3XplVsmVzi7P1GCW7kLtTCUUoQhGKUIQiFKEIRShCEYpQhCIUoQhFqKeE2nLk4Lpv9URzCztXZnWqevAxDv7u3FVX0gITilCEIhShCEUoQhGKUIQiFKEIRShCEYpQHxZqrqGIDWVnAzV3Ykvup9hqxDals32OfRWhCEUoQhGKUIQiFKEIRShCEYpQhCIUoQj1JaGumMI57GI12RVtzgMUxn53bvdLjhWhCEUoQhGKUIQiFKEIRShCEYpQhCIUoQj1JaHm2qu/TFKsNIy1hLGeqGSPthgted+Y9SV3DKEIRShCEYpQhCIUoQhFKEIRilCEIhShCHW5UDc2FHN/fHCDt+zbqvZKzuRcLRizr3N/CUUoQhGKUIQiFKEIRShCEYpQhCIUoQhFqC8JdfBsbI3OVol28PW3VmPuIBmGhh96ocsjFKEIRShCGUpCGQZCEYpQhCIUoQwloQwDofa7vLVqYOx4Hxz32Ind6j1jy17SfHUqM9fzEopQhCIUoQhFKEIRilCEIhShCEUoQhGKUB8Wag6dj5dosX5q7n4qef0toLfyO5et1ycUoQhFKEIRilCEIhShCEUoQhGKUIQiFKFuE2prgzsbqLkWKXa8Yxt6BQ1zxV/Mgrn9Hbz5CEUoQhGKUIQiFKEIRShCEYpQhCIUoQhFqMuEOniQ5hI7onM7WmLBFrKxjnjrj2PbPXesCEUoQhGKUIQiFKEIRShCEYpQhCIUoQhFKELFi7A5sErqudhqxOgvqW47Z6PEzbm7nFCEIhShCEUoQhGKUIQiFKEIRShCEYpQhHpaqM5tuKIXmyOppJ4ruQjnytmtTjxWof5bCqEIRShCEYpQhCIUoQhFKEIRilCEIhShCPW0UM+3OVfUgnO6bb3C3Kmb61sPPnNs6d7v8ghFKEIRilCEIhShCEUoQhGKUIQiFKEIRai7G4pYaVji18HRiX1z7AAf/OO5I7pVCh8chju6PEIRilCEIhShCEUoQhGKUIQiFKEIRShCEepuoQ6uXWxlSyrF2ErGnmqrQ4z1nrFLZa72JRShCEUoQhGKUIQiFKEIRShCEYpQhCIUoQhVdmLnljJW7sSqzLkdnHvmWDkbazbnaCgpsglFKEIRilCEIhShCEUoQhGKUIQiFKEIRShClS/HOey2DnBsoGOvv/XMc9sd4ywGJaEIRShCEYpQhCIUoQhFKEIRilCEIhShCEWo7SP6QOW0NRxzL7jVx8VeYatu7qyMBxkhFKEIRShCEYpQhCIUoQhFKEIRilCEIhShnhJqDp3YFF7RbMZKpdipK1mNrXtxa/hj9SuhCEUoQhGKUIQiFKEIRShCEYpQhCIUoQj1llCxomSr25qb7wear62udu6olBSdsVpwbswIRShCEYpQhCIUoQhFKEIRilCEIhShCEWoLwkVm8JYjxDrp7bqmy0oY01urIEqEXmLfkIRilCEIhShCEUoQhGKUIQiFKEIRShCEYpQ2+XO1gHe2tG5im3rh2L3YslpL2nrYmeBUIQiFKEIRShCEYpQhCIUoQhFKEIRilCEIlS8U/udy8GBLpnR2Ase/N2D37xVOJbs79wbEYpQhCIUoQhFKEIRilCEIhShCEUoQhGKUIQqW9mtSZrrH2Otyq8jW9dkyS6U7GDL/44QilCEIhShCEUoQhGKUIQiFKEIRShCEYpQlwnVuSs3PvMVXV5J/RoblbnLbKue25orQhGKUIQiFKEIRShCEYpQhCIUoQhFKEIR6mmhOruerYE+OHYxKOeeeUvVry3OVjc9OKKEIhShCEUoQhGKUIQiFKEIRShCEYpQhCLU3UJtffMWZ1u1Uawmi3V5ncd7a/dLujxCEYpQhCIUoQhFKEIRilCEIhShCEUoQhGKUPPdx1wHEROq5PXnrJ9rY29UZu6e2LqQSso7QhGKUIQiFKEIRShCEYpQhCIUoQhFKEIRilADQsWmIVb9bL3R1iEsOTkHb6+5yens4glFKEIRilCEIhShCEUoQhGKUIQiFKEIRShCdXd5JTXZ1kNu1XNbJ7akntsahs62jlCEIhShCEUoQhGKUIQiFKEIRShCEYpQhPqSUFfUKL9Utg5hrOqaO3VbFercHl2xGmsVKqEIRShCEYpQhCIUoQhFKEIRilCEIhShCHW3UFcc74NF2FypFHuMrYHeKsK2mtySQ1eiOaEIRShCEYpQhCIUoQhFKEIRilCEIhShCPWWUCIihBIRQomIEEpEhFAiQigREUKJCKFERAglIkIoESGUiAihRIRQIiKEEhEhlIgQSkSEUCJCKBERQomIEEpECCUiQigRIZSICKFERAglIv35D0DCqtC1/MzsAAAAAElFTkSuQmCC';
            $output['pixCopiaCola'] = '00020101021226820014br.gov.bcb.pix2560qrpix-h.bradesco.com.br/9d36b84f-c70b-478f-b95c-12729b90ca255204000053039865406513.005802BR5905ASAAS6009JOINVILLE62070503***63043E7E';
        }

        if (strtolower($data->billingType) === 'credit_card') {
            $output['credit_card_brand'] = 'VISA';
            $output['credit_card_token'] = uniqid();
            $output['credit_card_last_digits'] = '1123';
        }

        return $output;
    }
}
